<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class IeAccountsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('ie_accounts')->delete();
        
        \DB::table('ie_accounts')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'ACUEDUCTO Y ALCANTARILLADO',
                'account' => '48149148609',
                'date_opening' => NULL,
                'status' => 2,
                'id_account_type' => 1,
                'state' => 1,
                'id_user' => 1,
                'created_at' => NULL,
                'updated_at' => '2023-06-20 20:16:27',
                'id_bank' => 2,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'ALIMENTACION',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'ALQUILER DE EQUIPOS Y MAQUINARIA',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'ALQUILER DE LOTES Y/O EDIFICACIONES',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'ANTICIPO DE CLIENTE',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'ASEO Y CAFETERIA',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'BIENESTAR LABORAL',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'CESANTIAS',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'COBRO RETEGARANTIA',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'COMBUSTIBLE Y LUBRICANTES',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'CONTRATO DE SERVICIOS',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'CUENTAS POR COBRAR',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'CUENTAS POR PAGAR',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'DERECHOS NOTARIALES',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'DESEMBOLSO DE CREDITO',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'DEVOLUCION DE GASTOS BANCARIOS',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'DEVOLUCION DE IMPUESTOS',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'DEVOLUCION DE PAGO ANTERIOR',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'DOTACION',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'EGRESO POR TRASLADO PROPIO',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'ELEMENTOS DE ASEO Y CAFETERIA',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'ELEMENTOS DE PROTECCION PERSONAL',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'EMBARGOS Y/O BLOQUEOS',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'ENERGIA',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'EQUIPOS DE SEGURIDAD',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'EQUIPOS DE TECNOLOGIA',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'EQUIPOS Y HERRAMIENTAS',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'EQUIPOS Y MUEBLES DE OFICINA',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'EXÁMENES MEDICOS',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'FIC',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'FLOTA DE TRANSPORTE',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'FONDO NACIONAL DE GARANTIA',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'GASTOS/COMISIONES BANCARIOS',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'HONORARIOS PROFESIONALES',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'HOSPEDAJE',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'ICA',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'INGRESO POR TRASLADO PROPIO',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'INTERESES FINANCIEROS',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'INTERESES SOBRE CESANTIAS',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'INTERNET',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'IVA',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'LIQUIDACION LABORAL',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'LOTES Y EDIFICACIONES',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'MANTENIMIENTO Y REPARACIONES DE ACTIVOS',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'MATERIALES DE CONSTRUCCION',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'MENSAJERIA',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'MULTAS Y SANCIONES',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'N/A',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'OTRAS COMISIONES FINANCIERAS',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'OTROS INGRESOS',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'PAGO DE CAPITAL',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'PAGO DE TARJETA DE CREDITO',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'name' => 'PAGO POR DEVOLUCION DE PAGO ANTERIOR',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'name' => 'POLIZAS Y SEGUROS',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'name' => 'PREDIAL',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'name' => 'PRIMAS',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'name' => 'RECAUDO DE CARTERA',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'name' => 'RECAUDO DEUDORES',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'name' => 'RECOBRO A ENTIDADES SS',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'name' => 'REG.PUBLICOS/CAMARA DE COMERCIO',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'name' => 'RENTA',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'name' => 'RETEFUENTE',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'name' => 'SALARIOS',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'name' => 'SEGURIDAD FISICA',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'name' => 'SEGURIDAD SOCIAL',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'name' => 'TELEFONIA CELULAR',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'name' => 'TELEFONIA FIJA',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'name' => 'TRANSPORTE',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'name' => 'UTILES Y PAPELERIA',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'name' => 'VACACIONES',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'name' => 'VEHICULAR ALCALDIA',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'name' => 'VEHICULAR GOBERNACION',
                'account' => '',
                'date_opening' => NULL,
                'status' => NULL,
                'id_account_type' => NULL,
                'state' => 1,
                'id_user' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'id_bank' => NULL,
            ),
        ));
        
        
    }
}