<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class IeIncomeExpensesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('ie_income_expenses')->delete();
        
        \DB::table('ie_income_expenses')->insert(array (
            0 => 
            array (
                'id' => 39,
                'id_company' => 2,
                'id_movement_type' => 4,
                'price' => '300000',
                'state' => 1,
                'id_user' => 1,
                'date' => NULL,
                'tipdoc' => NULL,
                'doc' => NULL,
                'tipcon' => NULL,
                'con' => '3000',
                'created_at' => '2023-06-22 20:10:32',
                'updated_at' => NULL,
                'observation' => NULL,
                'id_thirdparti' => 1,
            ),
            1 => 
            array (
                'id' => 40,
                'id_company' => 2,
                'id_movement_type' => 4,
                'price' => '300000000',
                'state' => 1,
                'id_user' => 1,
                'date' => NULL,
                'tipdoc' => NULL,
                'doc' => NULL,
                'tipcon' => NULL,
                'con' => '30',
                'created_at' => '2023-06-22 20:12:37',
                'updated_at' => NULL,
                'observation' => NULL,
                'id_thirdparti' => 1,
            ),
            2 => 
            array (
                'id' => 41,
                'id_company' => 1,
                'id_movement_type' => 4,
                'price' => '30000',
                'state' => 1,
                'id_user' => 1,
                'date' => NULL,
                'tipdoc' => NULL,
                'doc' => NULL,
                'tipcon' => NULL,
                'con' => '30',
                'created_at' => '2023-06-22 20:14:17',
                'updated_at' => NULL,
                'observation' => NULL,
                'id_thirdparti' => 1,
            ),
            3 => 
            array (
                'id' => 42,
                'id_company' => 1,
                'id_movement_type' => 4,
                'price' => '30000',
                'state' => 1,
                'id_user' => 1,
                'date' => NULL,
                'tipdoc' => NULL,
                'doc' => NULL,
                'tipcon' => NULL,
                'con' => '30',
                'created_at' => '2023-06-22 20:14:30',
                'updated_at' => NULL,
                'observation' => NULL,
                'id_thirdparti' => 1,
            ),
            4 => 
            array (
                'id' => 43,
                'id_company' => 1,
                'id_movement_type' => 4,
                'price' => '300000',
                'state' => 1,
                'id_user' => 1,
                'date' => NULL,
                'tipdoc' => NULL,
                'doc' => NULL,
                'tipcon' => NULL,
                'con' => '30',
                'created_at' => '2023-06-22 20:15:28',
                'updated_at' => NULL,
                'observation' => NULL,
                'id_thirdparti' => 1,
            ),
            5 => 
            array (
                'id' => 44,
                'id_company' => 1,
                'id_movement_type' => 4,
                'price' => '300000',
                'state' => 1,
                'id_user' => 1,
                'date' => NULL,
                'tipdoc' => NULL,
                'doc' => NULL,
                'tipcon' => NULL,
                'con' => '30',
                'created_at' => '2023-06-22 20:17:46',
                'updated_at' => NULL,
                'observation' => NULL,
                'id_thirdparti' => 1,
            ),
            6 => 
            array (
                'id' => 45,
                'id_company' => 1,
                'id_movement_type' => 4,
                'price' => '300000',
                'state' => 1,
                'id_user' => 1,
                'date' => NULL,
                'tipdoc' => NULL,
                'doc' => NULL,
                'tipcon' => NULL,
                'con' => '30',
                'created_at' => '2023-06-22 20:18:08',
                'updated_at' => NULL,
                'observation' => NULL,
                'id_thirdparti' => 1,
            ),
            7 => 
            array (
                'id' => 46,
                'id_company' => 1,
                'id_movement_type' => 4,
                'price' => '300000',
                'state' => 1,
                'id_user' => 1,
                'date' => NULL,
                'tipdoc' => NULL,
                'doc' => NULL,
                'tipcon' => NULL,
                'con' => '30',
                'created_at' => '2023-06-22 20:23:40',
                'updated_at' => NULL,
                'observation' => NULL,
                'id_thirdparti' => 1,
            ),
            8 => 
            array (
                'id' => 47,
                'id_company' => 2,
                'id_movement_type' => 4,
                'price' => '300000',
                'state' => 1,
                'id_user' => 1,
                'date' => NULL,
                'tipdoc' => NULL,
                'doc' => NULL,
                'tipcon' => NULL,
                'con' => '30',
                'created_at' => '2023-06-22 20:24:01',
                'updated_at' => NULL,
                'observation' => 'ALGO DE OBSERVACIÓN',
                'id_thirdparti' => 1,
            ),
            9 => 
            array (
                'id' => 48,
                'id_company' => 1,
                'id_movement_type' => 4,
                'price' => '300000',
                'state' => 1,
                'id_user' => 1,
                'date' => NULL,
                'tipdoc' => NULL,
                'doc' => NULL,
                'tipcon' => NULL,
                'con' => '30',
                'created_at' => '2023-06-22 20:26:51',
                'updated_at' => NULL,
                'observation' => NULL,
                'id_thirdparti' => 1,
            ),
            10 => 
            array (
                'id' => 49,
                'id_company' => 1,
                'id_movement_type' => 4,
                'price' => '300000',
                'state' => 1,
                'id_user' => 1,
                'date' => NULL,
                'tipdoc' => NULL,
                'doc' => NULL,
                'tipcon' => NULL,
                'con' => '30',
                'created_at' => '2023-06-22 20:27:40',
                'updated_at' => NULL,
                'observation' => NULL,
                'id_thirdparti' => 1,
            ),
            11 => 
            array (
                'id' => 50,
                'id_company' => 1,
                'id_movement_type' => 4,
                'price' => '3000000',
                'state' => 1,
                'id_user' => 1,
                'date' => NULL,
                'tipdoc' => NULL,
                'doc' => NULL,
                'tipcon' => NULL,
                'con' => '30',
                'created_at' => '2023-06-22 20:27:55',
                'updated_at' => NULL,
                'observation' => NULL,
                'id_thirdparti' => 1,
            ),
            12 => 
            array (
                'id' => 51,
                'id_company' => 1,
                'id_movement_type' => 4,
                'price' => '85545454',
                'state' => 1,
                'id_user' => 1,
                'date' => NULL,
                'tipdoc' => NULL,
                'doc' => NULL,
                'tipcon' => NULL,
                'con' => '48487544',
                'created_at' => '2023-06-22 20:36:28',
                'updated_at' => NULL,
                'observation' => NULL,
                'id_thirdparti' => 1,
            ),
            13 => 
            array (
                'id' => 52,
                'id_company' => 1,
                'id_movement_type' => 4,
                'price' => '85545454',
                'state' => 1,
                'id_user' => 1,
                'date' => NULL,
                'tipdoc' => NULL,
                'doc' => NULL,
                'tipcon' => NULL,
                'con' => '48487544',
                'created_at' => '2023-06-22 20:45:40',
                'updated_at' => NULL,
                'observation' => NULL,
                'id_thirdparti' => 1,
            ),
            14 => 
            array (
                'id' => 53,
                'id_company' => 1,
                'id_movement_type' => 4,
                'price' => '30000000',
                'state' => 1,
                'id_user' => 1,
                'date' => NULL,
                'tipdoc' => NULL,
                'doc' => NULL,
                'tipcon' => NULL,
                'con' => '30',
                'created_at' => '2023-06-22 20:49:10',
                'updated_at' => NULL,
                'observation' => 'NO SE ALGO',
                'id_thirdparti' => 1,
            ),
            15 => 
            array (
                'id' => 54,
                'id_company' => 1,
                'id_movement_type' => 4,
                'price' => '30000000',
                'state' => 1,
                'id_user' => 1,
                'date' => NULL,
                'tipdoc' => NULL,
                'doc' => NULL,
                'tipcon' => NULL,
                'con' => '30',
                'created_at' => '2023-06-22 21:32:39',
                'updated_at' => NULL,
                'observation' => 'NO SE ALGO',
                'id_thirdparti' => 1,
            ),
            16 => 
            array (
                'id' => 55,
                'id_company' => 1,
                'id_movement_type' => 4,
                'price' => '30000000',
                'state' => 1,
                'id_user' => 1,
                'date' => NULL,
                'tipdoc' => NULL,
                'doc' => NULL,
                'tipcon' => NULL,
                'con' => '30',
                'created_at' => '2023-06-22 21:32:48',
                'updated_at' => NULL,
                'observation' => 'NO SE ALGO',
                'id_thirdparti' => 1,
            ),
            17 => 
            array (
                'id' => 56,
                'id_company' => 1,
                'id_movement_type' => 4,
                'price' => '30000000',
                'state' => 1,
                'id_user' => 1,
                'date' => NULL,
                'tipdoc' => NULL,
                'doc' => NULL,
                'tipcon' => NULL,
                'con' => '30',
                'created_at' => '2023-06-22 21:33:01',
                'updated_at' => NULL,
                'observation' => 'NO SE ALGO',
                'id_thirdparti' => 1,
            ),
            18 => 
            array (
                'id' => 57,
                'id_company' => 2,
                'id_movement_type' => 1,
                'price' => '500000',
                'state' => 1,
                'id_user' => 1,
                'date' => NULL,
                'tipdoc' => NULL,
                'doc' => NULL,
                'tipcon' => NULL,
                'con' => '30',
                'created_at' => '2023-06-22 21:34:22',
                'updated_at' => NULL,
                'observation' => NULL,
                'id_thirdparti' => 1,
            ),
            19 => 
            array (
                'id' => 58,
                'id_company' => 2,
                'id_movement_type' => 4,
                'price' => '500000',
                'state' => 1,
                'id_user' => 1,
                'date' => NULL,
                'tipdoc' => NULL,
                'doc' => NULL,
                'tipcon' => NULL,
                'con' => '30',
                'created_at' => '2023-06-22 21:39:34',
                'updated_at' => NULL,
                'observation' => 'ALGO DE OBSERVACIÓN',
                'id_thirdparti' => 1,
            ),
        ));
        
        
    }
}